version: '3'

services:
  pandapass:
    container_name: pandapass
    build:
      context: ./
      dockerfile: Dockerfile

    restart: always

networks: 
  default: 
    external: true
    name: external